name: uw3
channels:
  - conda-forge
dependencies:
  - python <= 3.11
  - compilers
  - mpich
  - petsc=3.21.5
  - petsc4py=3.21.5
  - cython=3.*
  - mpmath<=1.3
  - mesalib
  - pyvista
  - pykdtree
  - pytest
  - pytest-mpi
  - numpy<2
  - scipy>=1.15
  - sympy>=1.13
  - ipython
  - mpi4py
  - h5py=*=mpi*
  - gmsh
  - python-gmsh
  - python-xxhash
  - jupytext
  - pygments
  - pint>=0.24
  - cmocean
  - colorcet
  - imageio
  - imageio-ffmpeg
  - ipywidgets<9.0.0
  - jupyter-server-proxy
  - jupyterlab<5.0.0
  - trame>=2.5.2
  - trame-vtk>=2.5.8
  - trame-vuetify>=2.3.1
  - trimesh
  - typeguard
  - pydantic>=2
  - pyyaml
  - pip
  - pip:
      - rich<14
      - meshio
      - pygmsh
