name: uw3
channels:
  - conda-forge
dependencies:
  - python=3.11
  - compilers
  - mpich
  - petsc=3.21.5
  - petsc4py=3.21.5
  - cython=3.*
  - mpmath<=1.3
  - mesalib
  - pyvista
  - pykdtree
  - pytest
  - numpy
  - scipy
  - sympy
  - ipython
  - mpi4py
  - h5py=*=mpi*
  - trame
  - ipywidgets
  - gmsh
  - python-gmsh
  - python-xxhash
  - jupyterlab
  - jupytext
  - trame-vtk
  - trame-vuetify
  - pygments
  - pint
  - typeguard
  - pip
  # - pip:
  #   - gmsh-api # is this used still in UW?
