name: API docs / jupyterbook

# We should trigger this from an upload event 

on:
  push:   # We publish the beta docs as well
    branches: 
      - main 
    #   - development

  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      
      - uses: actions/checkout@v3

      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      #     cache: 'pip' # caching pip dependencies
          
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      #     # cache: 'npm'
          
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ./.github/workflows/envs/build_jb.yml
          cache-downloads: true

      # - name: install jupyterbook dependencies
      #   run: |
      #     pip install jupyter-book
      #     pip install jupytext
          
      - name: Build docs with jupyterbook
        shell: bash -l {0}
        run: |
          cd Jupyterbook
          ./build_book.sh 


      ## Always deploy to version directory
      - name: Deploy JB
        uses: peaceiris/actions-gh-pages@v3
        
        with:
          # deploy_key: ${{ secrets.GH_PAGES_DEPLOY_PR_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: ${{ github.ref_name }}    # The dest dir is identified by branch 
          publish_dir: jupyterbook/_build/html
          


 
